export const s = {
  formBox: {
    display: 'flex',
    flexWrap: { xs: 'wrap', sm: 'wrap', md: 'nowrap' },
    justifyContent: 'center',
    gap: { xs: '0px', sm: '0px', md: '350px' },
    paddingBottom: { xs: '52px' },
  },

  buttonsWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '20px',
    marginBottom: '20px',
  },
  activeButton: {
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#fff',
    width: '110px',
    height: '35px',
    userSelect: 'none',
    backgroundColor: ' #363c5c',
    borderRadius: '4px 0px 0px 4px',
    border: '2px solid #363c5c',
  },
  disableButton: {
    cursor: 'pointer',
    border: '2px solid #363c5c',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#000',
    width: '110px',
    height: '35px   ',
    backgroundColor: ' #fff',
    borderRadius: '0px 4px 4px 0px',
    userSelect: 'none',
    transition: 'all 300ms',
    ':hover': {
      backgroundColor: '#e9e9e9',
    },
  },
  logoInputBox: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
  },
  logoButton: {
    cursor: 'pointer',
    position: 'absolute',
    color: 'blue',
    fontSize: '14px',
    right: -80,
    top: 53,
    userSelect: 'none',
  },
};
